language: node_js
node_js:
- node
notifications:
  slack:
    secure: JOtjxlUzpPhw0HrW/iNQFEKn5GwUdb5lpOpQHIk+tqvLKMUGLHQ053VH7ihXMCG3d02Mrd/bI66zj6YOfMe+jtR4gRKDnlzhcaV/aZtdnXSUmmGbIVt6b9oMHVDnSPqzudDoHP6VtIRp1bimYpvbb6EHcwk0f+U0+t2leHdOfGXxUXFQuezLA74/XAhPP/PfqpCsQEv8oPSY5uqCfY75rK/5tpsTDUnDAuzUR1vkJD7PxztGZkLHetI28cgc/yIRzmuab/pJLNMweru8N/z3k2HX78Aw87MVzN2qspKGycS4hty2P0mWeneucc0bfvqJ1uyyyNdImp9U1CrCEXBPCqSNc12ux/wdCPRlLkoylwq+bBXlG8/PE3l4OKbesYfi3vQoOKwZPq+xWc3Z5tRShZWCp/OxBE20G27uh0SqV3DJE5LBXo3ShDVNIakspOPlCsKwrA3nNdaifFhlo70f737lF/45jb5hMD6AavSMG8ZEFQcPG4aqnZGyQJIHXLCCWkRDanzbDHHYYQ1tcM7r0YpktzI7rKX7LdZ2uYxHfamnF744X8iui7Wfanw9sL9MTg9dIQMHVNkTlufia8oJ5SCDS44TfdMCPH8XYw6HrRlLjqyrlSFqZo5SHJIyXezAp2l6oSIFAgYanHyxo2Jwz7uWfg1rQ5Mr1gei3Zhp/3o=
